#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg BASE_IMAGE="lts-buster-slim" \
    --build-arg JAVA_MAJOR_VERSION="11" \
    --build-arg JAVA_MINOR_REVISION="0.5" \
    --build-arg JAVA_BUILD_NUMBER="10" \
    --build-arg ESUM="6dd0c9c8a740e6c19149e98034fba8e368fd9aa16ab417aa636854d40db1a161" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
