#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg BASE_IMAGE="lts-buster-slim" \
    --build-arg JAVA_VERSION="11.0.8_10" \
    --build-arg PYTHON_PIP_VERSION="20.2.2" \
    --build-arg PIP_DOWNLOAD_HASH="2739acb7ffe6814449fa80ffec68604ca48aa59d" \
    --build-arg PYTHON_GET_PIP_SHA256="d4d62a0850fe0c2e6325b2cc20d818c580563de5a2038f917e3cb0e25280b4d1" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
