language: generic

services:
  - docker
  
env:
  matrix:
    - DIR=base
    - DIR=jshell
    - DIR=rust
    - DIR=sbt-console
    - DIR=xtermjs
    - DIR=xtermjs-rust
    - DIR=xtermjs-jshell
    - DIR=xtermjs-sbt-console


script:
  - CUR=$(pwd) &&
    cd ${DIR} &&
    if [ "$TRAVIS_PULL_REQUEST" == "true" ]; then bash docker build --rm -t ${DOCKER_USERNAME}/web-terminal:${DIR} .; fi &&
    cd ${CUR}
jobs:
  include:
    - stage: build
    - stage: deploy
      branches:
        only:
          - master
      if: branch = master
      script:
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin && docker push ${DOCKER_USERNAME}/web-terminal:${DIR}

  