name: 'Get Owner from GitHub Token Action'
description: 'Get Owner from GitHub Token.'
author: 'Kenji Saito <ken-yo@mbr.nifty.com>'
branding:
  icon: 'terminal'
  color: 'yellow'
inputs:
  github_token:
    required: true
runs:
  using: 'docker'
  image: './Dockerfile'
