#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg BASE_IMAGE="bionic" \
    --build-arg SBT_VERSION="1.4.3" \
    --build-arg JAVA_VERSION="11.0.9.1_11" \
    --build-arg PYTHON_PIP_VERSION="20.2.4" \
    --build-arg PIP_DOWNLOAD_HASH="fa7dc83944936bf09a0e4cb5d5ec852c0d256599" \
    --build-arg PYTHON_GET_PIP_SHA256="6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c" \
    --build-arg SWIFT_VERSION="5.3.1" \
    --build-arg SWIFT_SIGNING_KEY="A62AE125BBBFBB96A6E042EC925CC1CCED3D1561" \
    --build-arg SWIFT_PLATFORM_COMMA_LESS="ubuntu2004" \
    --build-arg SWIFT_PLATFORM="ubuntu20.04" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
