#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg BASE_IMAGE="lts-buster-slim" \
    --build-arg SBT_VERSION="1.3.7" \
    --build-arg JAVA_VERSION="11.0.6_10" \
    --build-arg PYTHON_VERSION="3.8.1" \
    --build-arg PYTHON_PIP_VERSION="20.0.2" \
    --build-arg PYTHON_XZ_GPG_KEY="E3FF2839C048B25C084DEBE9B26995E310250568" \
    --build-arg PIP_DOWNLOAD_HASH="42ad3426cb1ef05863521d7988d5f7fec0c99560" \
    --build-arg PYTHON_GET_PIP_SHA256="da288fc002d0bb2b90f6fbabc91048c1fa18d567ad067ee713c6e331d3a32b45" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
