#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg BASE_IMAGE="lts-buster-slim" \
    --build-arg SBT_VERSION="1.3.6" \
    --build-arg JAVA_VERSION="11.0.5_10" \
    --build-arg PYTHON_VERSION="3.8.0" \
    --build-arg PYTHON_PIP_VERSION="19.3.1" \
    --build-arg PYTHON_XZ_GPG_KEY="E3FF2839C048B25C084DEBE9B26995E310250568" \
    --build-arg PIP_DOWNLOAD_HASH="ffe826207a010164265d9cc807978e3604d18ca0" \
    --build-arg PYTHON_GET_PIP_SHA256="b86f36cc4345ae87bfd4f10ef6b2dbfa7a872fbff70608a1e43944d283fd0eee" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
