name: git-secrets action example
 
on:
  push:
    branches:    
    - master 
  schedule:
    - cron:  '* * * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker://node:lts-buster-slim
    - run: ./update.sh
    - name: Commit files
      run: |
        git config --local user.email "ken-yo@mbr.nifty.com"
        git config --local user.name "Kenji Saito"
        TIMESTAMP=$(date)
        BRANCH_NAME="feature/bump-modules-$(date "+%Y%m%d-%H%M%S")"
        git checkout -b "${BRANCH_NAME}"
        git add *
        git commit -m "Auto update at ${TIMESTAMP}"
        echo "::set-env name=BRANCH_NAME::${BRANCH_NAME}"
        echo "::set-env name=TIMESTAMP::${TIMESTAMP}"

    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
        branch: ${{ env.BRANCH_NAME }}
    - name: Create pull request
      uses: ./.github/actions
      with:
        branch_name: ${{ env.BRANCH_NAME }}
        title: ${{ format('Auto update at {0}', env.TIMESTAMP) }}
        body: ${{ format('Update the modules at {0}', env.TIMESTAMP) }}
        github_token: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
        repository: ${{ github.repository }}
