name: Node.js modules auto update
 
on:
  push:
    branches:    
    - master 
#  schedule:
#    - cron:  '* * * * 3'

jobs:
  auto_update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker://node:lts-buster-slim
    - run: ./update.sh
    - name: Commit files
      run: |
        git config --local user.email "ken-yo@mbr.nifty.com"
        git config --local user.name "Kenji Saito"
        TIMESTAMP=$(date)
        BRANCH_NAME="feature/bump-modules-$(date "+%Y%m%d-%H%M%S")"
        git checkout -b "${BRANCH_NAME}"
        git add *
        git commit -m "Auto update at ${TIMESTAMP}"
        echo "::set-env name=BRANCH_NAME::${BRANCH_NAME}"
        echo "::set-env name=TIMESTAMP::${TIMESTAMP}"
    - name: Get Token Owner
      if: success()
      run: |
        sudo apt update -qq
        sudo apt install -qqy --no-install-recommends curl jq
        USER=$(curl -H "Authorization: token ${GITHUB_TOKEN_OWNER}" https://api.github.com/user)
        USER_ID=$(echo ${USER} | jq ".login")
        echo "::set-env name=GITHUB_TOKEN_OWNER::${USER_ID}"
    - name: Push Changes
      if: success()
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
        branch: ${{ env.BRANCH_NAME }}
    - name: Create pull request
      id: create_pull_request
      if: success()
      uses: ./.github/actions/create_pull_request
      with:
        branch_name: ${{ env.BRANCH_NAME }}
        title: ${{ format('Auto update at {0}', env.TIMESTAMP) }}
        body: ${{ format('Update the modules at {0}', env.TIMESTAMP) }}
        github_token: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
        repository: ${{ github.repository }}
    - name: Assign to pull request
      if: success()
      uses: ./.github/actions/assign_reviewer
      with:
        pull_request_url: ${{ env.PULL_REQUEST_URL }}
        requested_reviewer: ${{ env.GITHUB_TOKEN_OWNER }}
        github_token: ${{ secrets.GITHUB_ACTIONS_TOKEN }}

