name: Node.js modules auto update and Docker Image push

on:
  pull_request:
    branches:
      - master
  push:
    branches:    
    - master 
  schedule:
    - cron:  '0 0 * * 3'

jobs:
  auto_update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      if: github.event_name != 'pull_request'
    - uses: docker://node:lts-buster-slim
      if: github.event_name != 'pull_request'
    - run: ./update.sh
      if: github.event_name != 'pull_request'
    - name: Commit files
      if: github.event_name != 'pull_request'
      run: |
        git config --local user.email "ken-yo@mbr.nifty.com"
        git config --local user.name "Kenji Saito"
        TIMESTAMP=$(date)
        BRANCH_NAME="feature/bump-modules-$(date "+%Y%m%d-%H%M%S")"
        git checkout -b "${BRANCH_NAME}"
        if [ $(git diff | wc -l) -eq 0 ]; then
          echo "::set-env name=CHANGE_STATE::no_changed"
          exit 0
        fi
        git add *
        git commit -m "Auto update at ${TIMESTAMP}"
        echo "::set-env name=BRANCH_NAME::${BRANCH_NAME}"
        echo "::set-env name=TIMESTAMP::${TIMESTAMP}"
        echo "::set-env name=CHANGE_STATE::changed"
    - name: Push Changes
      if: success() && env.CHANGE_STATE == 'changed' && github.event_name != 'pull_request'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}
        branch: ${{ env.BRANCH_NAME }}
    - name: Create pull request
      if: success() && env.CHANGE_STATE == 'changed' && github.event_name != 'pull_request'
      uses: ./.github/actions/create_pull_request
      with:
        branch_name: ${{ env.BRANCH_NAME }}
        title: ${{ format('Auto update at {0}', env.TIMESTAMP) }}
        body: ${{ format('Update the modules at {0}', env.TIMESTAMP) }}
        github_token: ${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}
        repository: ${{ github.repository }}
    - name: Send result with Pull Request
      if: success() && env.CHANGE_STATE == 'changed' && github.event_name != 'pull_request'
      uses: ./.github/actions/slack_notificator
      with:
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        text: ${{ format('{0} {1}\nPull Request <{2}>', github.workflow, job.status, env.PULL_REQUEST_HTML_URL) }}

    - name: Send result without Pull Request
      if: success() && env.CHANGE_STATE != 'changed' && github.event_name != 'pull_request'
      uses: ./.github/actions/slack_notificator
      with:
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        text: ${{ format('{0} {1}', github.workflow, job.status) }}

  docker_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          'xtermjs',
          'jshell',
          'rust',
          'sbt-console',
          'swift'
        ]
    steps:
    - uses: actions/checkout@master
      if: github.event_name == 'pull_request' && github.event_name != 'schedule'
    - name: Build ${{ matrix.target }}
      if: github.event_name == 'pull_request' && github.event_name != 'schedule'
      env:
        DOCKER_BUILDKIT: 1
      run: |
        CUR=$(pwd) && \
        cd xtermjs && \
        docker build --rm --target "${{ matrix.target }}" -t "poad/web-terminal:${{ matrix.target }}" . && \
        cd ${CUR}
    - name: Hadolint
      if: github.event_name == 'pull_request' && github.event_name != 'schedule'
      uses: brpaz/hadolint-action@master
      with:
        dockerfile: xtermjs/Dockerfile
  
  docker_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          'xtermjs',
          'jshell',
          'rust',
          'sbt-console',
          'swift'
        ]
    steps:
    - uses: actions/checkout@master
      if: github.event_name != 'pull_request'
    - name: Build ${{ matrix.target }} and push
      if: github.event_name != 'pull_request'
      env:
        DOCKER_BUILDKIT: 1
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u poad --password-stdin && \
        CUR=$(pwd) && \
        cd xtermjs && \
        docker build --rm --target "${{ matrix.target }}" -t "poad/web-terminal:${{ matrix.target }}" . && \
        docker push "poad/web-terminal:${{ matrix.target }}" && \
        cd ${CUR}
